name: Deploy to Production

on:
  push:
    # Match against refs/heads
    branches:    
      - main
    # Deploy on any refs/tags
    tags: 
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Do something
        run: echo "Now I will do the deploy to prod!!!!"
